[default]

[development]
SECRET_KEY = '\x94$L\xff\xf9\xfe6S\x8e\xe6@\xcac\xf9ND'
JWT_SECRET_KEY = '\xe0F/M\xa9`\xf7+v\xa1rh\n\x07\x11\xf3'

[production]
SECRET_KEY = '\x94$L\xff\xf9\xfe6S\x8e\xe6@\xcac\xf9ND'
JWT_SECRET_KEY = '\xe0F/M\xa9`\xf7+v\xa1rh\n\x07\x11\xf3'