[default]
DEBUG = false
EXTENSIONS = [
    "bookmarks.ext.sqlalchemy:init_app",
    "bookmarks.ext.migrate:init_app",
    "bookmarks.controllers:init_app",
    "bookmarks.ext.jwt_manager:init_app",
    "bookmarks.controllers.api.redirect_to_url:init_app",
    "bookmarks.services.error_handler:init_app",
    "bookmarks.ext.flasgger:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "bookmarks.ext.sqlalchemy:init_app",
    "bookmarks.ext.migrate:init_app",
    "bookmarks.controllers:init_app",
    "bookmarks.ext.jwt_manager:init_app",
    "bookmarks.controllers.api.redirect_to_url:init_app",
    "bookmarks.services.error_handler:init_app",
    "bookmarks.ext.flasgger:init_app",
]
SWAGGER = {title='Bookmarks API', uiversion=3}

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "bookmarks.ext.sqlalchemy:init_app",
    "bookmarks.ext.migrate:init_app",
    "bookmarks.controllers:init_app",
    "bookmarks.ext.jwt_manager:init_app",
    "bookmarks.controllers.api.redirect_to_url:init_app",
    "bookmarks.services.error_handler:init_app",
    "bookmarks.ext.flasgger:init_app",
]
SWAGGER = {title='Bookmarks API', uiversion=3}
