[default]
DEBUG = false
EXTENSIONS = [
    "bookmarks.database:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "bookmarks.database:init_app",
    "bookmarks.database.migrate:init_app",
    "bookmarks.blueprints:init_app",
]

[production]
EXTENSIONS = [
    "bookmarks.database:init_app",
]
