[default]
DEBUG = false
SECRET_KEY = '\x94$L\xff\xf9\xfe6S\x8e\xe6@\xcac\xf9ND'
JWT_SECRET_KEY = '\xe0F/M\xa9`\xf7+v\xa1rh\n\x07\x11\xf3'
SQLALCHEMY_DATABASE_URI = 'postgresql://gqmpdkznhymvrs:94de9ff5431166f339c68cd451fb7f76dd7cb366ce0b14761db758dd2e85a3a4@ec2-54-80-122-11.compute-1.amazonaws.com:5432/d9p5qucpbp9ec'
EXTENSIONS = [
    "bookmarks.ext.sqlalchemy:init_app",
    "bookmarks.ext.migrate:init_app",
    "bookmarks.controllers:init_app",
    "bookmarks.ext.jwt_manager:init_app",
    "bookmarks.controllers.api.redirect_to_url:init_app",
    "bookmarks.services.error_handler:init_app",
    "bookmarks.ext.flasgger:init_app",
]

[development]
DEBUG = true
SECRET_KEY = '\x94$L\xff\xf9\xfe6S\x8e\xe6@\xcac\xf9ND'
JWT_SECRET_KEY = '\xe0F/M\xa9`\xf7+v\xa1rh\n\x07\x11\xf3'
SQLALCHEMY_DATABASE_URI = 'postgresql://gqmpdkznhymvrs:94de9ff5431166f339c68cd451fb7f76dd7cb366ce0b14761db758dd2e85a3a4@ec2-54-80-122-11.compute-1.amazonaws.com:5432/d9p5qucpbp9ec'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "bookmarks.ext.sqlalchemy:init_app",
    "bookmarks.ext.migrate:init_app",
    "bookmarks.controllers:init_app",
    "bookmarks.ext.jwt_manager:init_app",
    "bookmarks.controllers.api.redirect_to_url:init_app",
    "bookmarks.services.error_handler:init_app",
    "bookmarks.ext.flasgger:init_app",
]
SWAGGER = {title='Bookmarks API', uiversion=3}

[production]
SECRET_KEY = '\x94$L\xff\xf9\xfe6S\x8e\xe6@\xcac\xf9ND'
JWT_SECRET_KEY = '\xe0F/M\xa9`\xf7+v\xa1rh\n\x07\x11\xf3'
SQLALCHEMY_DATABASE_URI = 'postgresql://gqmpdkznhymvrs:94de9ff5431166f339c68cd451fb7f76dd7cb366ce0b14761db758dd2e85a3a4@ec2-54-80-122-11.compute-1.amazonaws.com:5432/d9p5qucpbp9ec'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "bookmarks.ext.sqlalchemy:init_app",
    "bookmarks.ext.migrate:init_app",
    "bookmarks.controllers:init_app",
    "bookmarks.ext.jwt_manager:init_app",
    "bookmarks.controllers.api.redirect_to_url:init_app",
    "bookmarks.services.error_handler:init_app",
    "bookmarks.ext.flasgger:init_app",
]
SWAGGER = {title='Bookmarks API', uiversion=3}
