[default]
DEBUG = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "bookmarks.ext.sqlalchemy:init_app",
    "bookmarks.ext.migrate:init_app",
    "bookmarks.controllers:init_app",
    "bookmarks.ext.jwt_manager:init_app",
    "bookmarks.controllers.redirect_to_url:init_app",
    "bookmarks.services.error_handler:init_app",
    "bookmarks.ext.flasgger:init_app",
]
SWAGGER = {title='Bookmarks API', uiversion=3}
JWT_ACCESS_TOKEN_EXPIRES = 86400

[development]
DEBUG = true

[production]
