"""bookmark.password attribute changed to bookmark.body

Revision ID: 0576b8b6cd15
Revises: e7f63d065b93
Create Date: 2022-04-15 11:05:35.034575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0576b8b6cd15'
down_revision = 'e7f63d065b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('body', sa.Text(), nullable=True))
    op.drop_column('bookmarks', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('password', sa.TEXT(), nullable=True))
    op.drop_column('bookmarks', 'body')
    # ### end Alembic commands ###
